import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://parabank.parasoft.com/parabank/index.htm")
    page.get_by_role("heading", name="Customer Login").click()
    page.get_by_text("Username").click()
    page.locator("input[name=\"username\"]").click()
    page.get_by_text("Password").click()
    page.locator("input[name=\"password\"]").click()
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("link", name="Forgot login info?").click()
    page.get_by_role("heading", name="Customer Lookup").click()
    page.get_by_text("Please fill out the following").click()
    page.locator("#firstName").click()
    page.get_by_text("First Name:").click()
    page.locator("#firstName").click()
    page.get_by_text("Last Name:").click()
    page.locator("#lastName").click()
    page.get_by_text("Address:").click()
    page.locator("[id=\"address.street\"]").click()
    page.get_by_text("City:").click()
    page.locator("[id=\"address.city\"]").click()
    page.get_by_text("State:").click()
    page.locator("[id=\"address.state\"]").click()
    page.get_by_text("Zip Code:").click()
    page.locator("[id=\"address.zipCode\"]").click()
    page.get_by_text("SSN:").click()
    page.locator("#ssn").click()
    page.get_by_role("button", name="Find My Login Info").click()
    page.get_by_text("Customer Lookup Please fill").click()
    page.get_by_role("link", name="Register").click()
    page.get_by_role("heading", name="Signing up is easy!").click()
    page.get_by_text("If you have an account with").click()
    page.get_by_text("First Name:").click()
    page.locator("[id=\"customer.firstName\"]").click()
    page.get_by_text("Last Name:").click()
    page.locator("[id=\"customer.lastName\"]").click()
    page.get_by_text("Address:").click()
    page.locator("[id=\"customer.address.street\"]").click()
    page.get_by_text("City:").click()
    page.locator("[id=\"customer.address.city\"]").click()
    page.get_by_role("cell", name="City:").click()
    page.get_by_text("State:").click()
    page.locator("[id=\"customer.address.state\"]").click()
    page.get_by_text("Zip Code:").click()
    page.locator("[id=\"customer.address.zipCode\"]").click()
    page.get_by_text("Phone #:").click()
    page.locator("[id=\"customer.phoneNumber\"]").click()
    page.get_by_text("SSN:").click()
    page.locator("[id=\"customer.ssn\"]").click()
    page.get_by_text("Username:").click()
    page.locator("[id=\"customer.username\"]").click()
    page.get_by_text("Password:").click()
    page.locator("[id=\"customer.password\"]").click()
    page.get_by_text("Confirm:").click()
    page.get_by_text("Confirm:").click()
    page.locator("#repeatedPassword").click()
    page.get_by_role("button", name="Register").click()
    page.locator("input[name=\"username\"]").click()
    page.locator("input[name=\"username\"]").fill("john")
    page.locator("input[name=\"username\"]").press("Tab")
    page.locator("input[name=\"password\"]").fill("demo")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("link", name="Open New Account").click()
    page.locator("#rightPanel").click()
    page.get_by_text("What type of Account would").click()
    page.locator("body").click()
    page.locator("#type").select_option("1")
    page.get_by_text("A minimum of $100.00 must be").click()
    page.locator("#fromAccountId").select_option("14454")
    page.get_by_role("button", name="Open New Account").click()
    page.get_by_role("link", name="Find Transactions").click()
    page.get_by_role("link", name="Request Loan").click()
    page.get_by_role("heading", name="Apply for a Loan").click()
    page.get_by_text("Apply for a Loan Loan Amount").click()
    page.get_by_text("Loan Amount:").click()
    page.get_by_role("cell", name="Loan Amount: $").click()
    page.locator("#amount").click()
    page.get_by_text("Down Payment:").click()
    page.get_by_role("cell", name="Down Payment: $").click()
    page.locator("#downPayment").click()
    page.get_by_text("From account #:").click()
    page.locator("#fromAccountId").select_option("14454")
    page.get_by_role("button", name="Apply Now").click()
    page.get_by_role("link", name="Log Out").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
